version: '3.3'

services: 
    wordpress:
        #build:
        #    dockerfile: ./Dockerfile
        #    context: .
        image: glendalaci/wordpress_teste:1.0.0
        restart: always
        ports: 
            - 8080:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: wppass
            WORDPRESS_DB_NAME: wpdb
        volumes: 
            - ./:/var/www/html
        networks: 
           back:
            ipv4_address: 10.165.11.220

    db:
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_DATABASE: wpdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wppass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes: 
            - db:/var/lib/mysql
        ports: 
            - 3306:3306
        networks: 
           back:

    adminer:
        depends_on: 
            - db
        image: adminer
        restart: always
        ports: 
            - 8888:8080

networks: 
    back:
      driver: bridge
      ipam:            
         config:
          - subnet: 10.165.10.0/23
            gateway: 10.165.11.254
        
volumes: 
    db: